export const billReleaseEInvoicesType = {
  LOADING: 'LOADING',
  GET_ALL: 'GET_ALL_BILL_RELEASE_EINVOICE',
  BILL_KIND:'GET_ALL_BILL_KIND_BILL_RELEASE_EINVOICE',
  INSERT: 'INSERT_BILL_RELEASE_EINVOICE',
  UPDATE: 'UPDATE_BILL_RELEASE_EINVOICE',
  DELETE: 'DELETE_BILL_RELEASE_EINVOICE',
};
