export const eInvoiceTemplateInputTypes = {
    GET_ALL_EINVOICE_TEMPLATE: "GET_ALL_EINVOICE_TEMPLATE",
    GET_ALL_EINVOICE_TEMPLATE_INPUT: "GET_ALL_EINVOICE_TEMPLATE_INPUT",
    GET_BY_ID_EINVOICE_TEMPLATE: "GET_BY_ID_EINVOICE_TEMPLATE",
    GET_REPORT_TEMPLATE: "GET_REPORT_TEMPLATE",
    GET_COMPANY_INFO: "GET_COMPANY_INFO",
    UPDATE_EINVOICE_TEMPLATE: "UPDATE_EINVOICE_TEMPLATE",
    DATA_SORT: "DATA_SORT",
    DATA_SEARCH: "DATA_SEARCH",
    LOADING: "LOADING",
}