export const formOfInvoicesTypes = {
    GET_ALL_EINVOICE_TEMPLATE: "GET_ALL_EINVOICE_TEMPLATE",
    GET_ALL_EINVOICE_TEMPLATE_INPUT: "GET_ALL_EINVOICE_TEMPLATE_INPUT",
    GET_BY_ID_EINVOICE_TEMPLATE: "GET_BY_ID_EINVOICE_TEMPLATE",
}