export const userTypes={
    SET_CURRENT_USER:"SET_CURRENT_USER",
    LOGIN_START:"LOGIN_START",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAIL:"LOGIN_FAIL",
    LOGOUT:"LOGOUT",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAIL:"LOGOUT_FAIL",
}